---
#Elegir uno de los dos nodos para monitorear, no se puedes elegir los dos
nodos:
  - "Minerva-11"
  #- "Minerva-12"


parametros: 
#Elegir qué parametros monitorear de entre los siguientes y Escoja los atributos concretos a monitorizar: (quitar el # para escogerlos)
#Si se elgie el parametro X hay que quitar el # como minimo del name, num, atributs i almmenos el de un atributo

  - name: AllMemtablesHeapSize
    num: 1
    atributs:
    - Value

  #- name: CompletedTasks
    #num: 2
    #atributs:
    #- Value

  #- name: Exceptions
    #num: 3
    #atributs:
    #- Count

  #- name: KeyCacheHitRate
    #num: 4
    #atributs:
    #- Value

  - name: KeyCacheHits
    num: 5
    atributs:
    - Count
    - FifteenMinuteRate
    - FiveMinuteRate
    - MeanRate
    - OneMinuteRate

  - name: KeyCacheMisses
    num: 6 
    atributs:
    - Count
    - FifteenMinuteRate
    - FiveMinuteRate
    - MeanRate
    - OneMinuteRate

 #- name: KeyCacheRequests
    #num: 7
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: ReadLatency
    #num: 8
    #atributs:
    #- 50thPercentile
    #- 75thPercentile
    #- 95thPercentile
    #- 98thPercentile
    #- 999thPercentile
    #- 99thPercentile
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- Max
    #- Mean
    #- MeanRate
    #- Min
    #- OneMinuteRate
    #- RecentValues
    #- StdDev

  #- name: ReadTimeOuts
    #num: 9
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: ReadTotalLatency
    #num: 10
    #atributs:
    #- Count

  #- name: ReadUnavailables
    #num: 11
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: RowCacheHitRate
    #num: 12
    #atributs:
    #- Value

  #- name: RowCacheHits
    #num: 13
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: RowCacheMisses
    #num: 14
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: RowCacheRequests
    #num: 15
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: TotalDiskSpaceUsed
    #num: 16
    #atributs:
    #- Value

  #- name: WriteLatency
    #num: 17
    #atributs:
    #- 50thPercentile
    #- 75thPercentile
    #- 95thPercentile
    #- 98thPercentile
    #- 999thPercentile
    #- 99thPercentile
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- Max
    #- Mean
    #- MeanRate
    #- Min
    #- OneMinuteRate
    #- RecentValues
    #- StdDev

  #- name: WriteTimeOuts
    #num: 18
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate

  #- name: WriteTotalLatency
    #num: 19
    #atributs:
    #- Count

  #- name: WriteUnavailables
    #num: 20
    #atributs:
    #- Count
    #- FifteenMinuteRate
    #- FiveMinuteRate
    #- MeanRate
    #- OneMinuteRate
